apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: storageclass-openebs
  resources:
    requests:
      storage: 1Gi
provisioner: openebs.io/provisioner-iscsi
